global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node-components
    static_configs:
      - targets:
          - "recall-exporter:9010"
          - "cometbft:26660"
          - "fendermint:9184"
          - "iroh:9090"
          - "objects:9186"
          - "ethapi:9185"
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/*.json
        - /etc/prometheus/targets/*.yml
    relabel_configs:
      - action: replace
        target_label: subnet_id
        replacement: "$subnet_id"
      - action: replace
        target_label: node_name
        replacement: "$node_name"
      - action: replace
        target_label: network_name
        replacement: "$network_name"


rule_files:
  - "/etc/prometheus/rules/*.yml"

