global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node-components
    static_configs:
      - targets:
          - "${project_name}-recall-exporter-1:9010"
          - "${project_name}-cometbft-1:26660"
          - "${project_name}-fendermint-1:9184"
          - "${project_name}-iroh-1:9090"
          - "${project_name}-objects-1:9186"
          - "${project_name}-ethapi-1:9185"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.json
          - /etc/prometheus/targets/*.yml
    relabel_configs:
      - action: replace
        target_label: subnet_id
        replacement: "$subnet_id"
      - action: replace
        target_label: node_name
        replacement: "$node_name"
      - action: replace
        target_label: network_name
        replacement: "$network_name"

rule_files:
  - "/etc/prometheus/rules/*.yml"
