keystore_path = "/relayer/ipc"

# Filecoin Calibration
[[subnets]]
id = "/r314159"

[subnets.config]
network_type = "fevm"
provider_http = "$parent_endpoint"
auth_token = "$parent_endpoint_token"
gateway_addr = "$parent_gateway_address"
registry_addr = "$parent_registry_address"

[[subnets]]
id = "$subnet_id"
[subnets.config]
network_type = "fevm"
provider_http = "http://ethapi:8545"

# These are static and deployed at subnet genesis
gateway_addr = "0x77aa40b105843728088c0132e43fc44348881da8"
registry_addr = "0x74539671a1d2f1c8f200826baba665179f53a1b7"
