name: ${project_name}-init

services:
  cometbft-init:
    image: $cometbft_image
    volumes:
      - $workdir/cometbft:/cometbft
    command: init --home /cometbft
    user: root

  genesis-from-peer:
    image: &utils ${project_name}-init-utils
    build:
      dockerfile: ./scripts/utils.Dockerfile
    volumes:
      - $workdir/cometbft:/cometbft
      - ./:/repo:ro
    command: /bin/bash /repo/scripts/download-genesis.sh
    depends_on:
      cometbft-init:
        condition: service_completed_successfully

  genesis:
    image: $fendermint_image
    volumes:
      - $workdir/cometbft:/cometbft
      - ./:/repo:ro
    entrypoint: /bin/bash /repo/scripts/download-genesis.sh
    depends_on:
      genesis-from-peer:
        condition: service_completed_successfully

  keys:
    image: $fendermint_image
    volumes:
      - ./:/repo:ro
      - $workdir:/workdir
    entrypoint: /bin/bash /repo/scripts/set-up-keys.sh

    depends_on:
      cometbft-init:
        condition: service_completed_successfully

  write-config:
    image: *utils
    volumes:
      - ./:/repo:ro
      - $workdir:/workdir
    command: bash /repo/scripts/write-configs.sh
    depends_on:
      keys:
        condition: service_completed_successfully

networks:
  default:
    name: $project_name
