name: $network_name

services:
  ipc-home-setup:
    build:
      dockerfile: ./init/Dockerfile
    volumes:
      - $ipc_home:/ipc
      - ./:/repo:ro
    command: nu /repo/scripts/init-ipc-config.nu

  cometbft-init:
    image: $cometbft_image
    volumes:
      - $cometbft_folder:/cometbft
    command: init --home /cometbft

  genesis:
    image: $fendermint_image
    volumes:
      - $cometbft_folder:/cometbft
      - ./:/repo:ro
    entrypoint: /bin/bash /repo/scripts/download-genesis.sh
    env_file: network-config.env
    depends_on:
      cometbft-init:
        condition: service_completed_successfully

  keys:
    image: $fendermint_image
    volumes:
      - ./:/repo:ro
      - $workdir:/workdir
    entrypoint: /bin/bash /repo/scripts/set-up-keys.sh
    env_file: network-config.env

    depends_on:
      cometbft-init:
        condition: service_completed_successfully

