name: ${project_name}-init

services:
  cometbft-init:
    image: $cometbft_image
    volumes:
      - $cometbft_dir:/cometbft
    command: init --home /cometbft

  genesis:
    image: $fendermint_image
    volumes:
      - $cometbft_dir:/cometbft
      - ./:/repo:ro
    entrypoint: /bin/bash /repo/init/download-genesis.sh
    env_file:
      - path: ./config/network-config.env
      - path: ./config/node.env
    depends_on:
      cometbft-init:
        condition: service_completed_successfully

  keys:
    image: $fendermint_image
    volumes:
      - ./:/repo:ro
      - $workdir:/workdir
    entrypoint: /bin/bash /repo/init/set-up-keys.sh
    env_file: &all-env
      - path: ./config/node-default.env
      - path: ./config/node.env
      - path: ./config/network-config.env

    depends_on:
      cometbft-init:
        condition: service_completed_successfully

  write-config:
    build: ./init
    volumes:
      - ./:/repo:ro
      - $workdir:/workdir
    command: sh /repo/init/write-configs.sh
    depends_on:
      cometbft-init:
        condition: service_completed_successfully
    env_file: *all-env

