name: ${project_name}-init

services:
  cometbft-init:
    image: $cometbft_image
    volumes:
      - $workdir/cometbft:/cometbft
    command: init --home /cometbft
    user: root

  genesis:
    image: $fendermint_image
    volumes:
      - $workdir/cometbft:/cometbft
      - ./:/repo:ro
    entrypoint: /bin/bash /repo/scripts/download-genesis.sh
    env_file:
      - path: ./config/network-${network_name}.env
      - path: ./config/node.env # secrets only
    depends_on:
      cometbft-init:
        condition: service_completed_successfully

  keys:
    image: $fendermint_image
    volumes:
      - ./:/repo:ro
      - $workdir:/workdir
    entrypoint: /bin/bash /repo/scripts/set-up-keys.sh

    depends_on:
      cometbft-init:
        condition: service_completed_successfully

  write-config:
    build:
      dockerfile: ./scripts/write-configs.Dockerfile
    volumes:
      - ./:/repo:ro
      - $workdir:/workdir
    command: bash /repo/scripts/write-configs.sh
    depends_on:
      keys:
        condition: service_completed_successfully

networks:
  default:
    name: $project_name
