network_name = "testnet"
node_name = "node-0"
project_name = "testnet-node-0"
datadir = "./data"

[images]
fendermint = "textile/fendermint:sha-567108a"
cometbft = "cometbft/cometbft:v0.37.x"
recall_exporter = "textilemachine/recall-exporter:sha-c6d1903"
prometheus = "prom/prometheus:v2.54.1"
registrar = "textilemachine/registrar:729f7f8"
recall_s3 = "textilemachine/recall-s3:sha-d4e3da3"

[networking]
docker_network_subnet = "192.168.55.0/24"
host_bind_ip = "127.0.0.1"

[networking.external_ports]
cometbft = 26656
fendermint = 26655
fendermint_iroh = 11204
objects_iroh = 11206

[services]
cometbft_statesync_enable = true
fendermint_snapshot_block_interval = 10000
relayer_checkpoint_interval_sec = 600

[relayer]
enable = false

[recall_s3]
enable = false

[registrar]
enable = false
trusted_proxy_ips = []

[prometheus]

[http_docker_network]

[localnet]
enable = false
