services:
  faucet:
    image: $faucet_image
    restart: always
    env_file:
      - $workdir/generated/faucet.env
    command:
      - bash
      - -c
      - |
        set -ex
        export TRUSTED_PROXY_IPS=$(getent hosts caddy | awk '{print $1}')
        /bin/app start

    depends_on:
      - ethapi
      - caddy
