services:
  cometbft:
    ports:
      - $localhost_cli_bind_host:26657:26657

  ethapi:
    ports:
      - $localhost_cli_bind_host:8645:8545

  objects:
    ports:
      - $localhost_cli_bind_host:8001:8001
