services:
  cometbft:
    ports:
      - $host_bind_ip:$external_cometbft_port:26656

  fendermint:
    ports:
      - $host_bind_ip:$external_fendermint_port:26655

  iroh:
    ports:
      - $host_bind_ip:$external_iroh_port:11204/udp
