services:
  registrar:
    image: $registrar_image
    restart: always
    env_file:
      - $workdir/generated/registrar.env
    depends_on:
      - ethapi
    networks:
      default:
        ipv4_address: $registrar_ip
