services:
  relayer:
    image: $fendermint_image
    entrypoint: sh /relayer/run.sh
    restart: always
    volumes:
      - $workdir/relayer:/relayer
    env_file:
      - ./config/network-${network_name}.env
    depends_on:
      - fendermint
    networks:
      default:
        ipv4_address: $relayer_ip
